# Generated by Django 3.2.6 on 2021-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('OFFICER', 'Distribution Officer'), ('MANAGER', 'Operations Manager'), ('SALESPERSON', 'Salesperson')], max_length=50),
        ),
    ]
