# Generated by Django 3.2.6 on 2021-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210810_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(max_length=255, upload_to='staff/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('SALESPERSON', 'Salesperson'), ('OFFICER', 'Distribution Officer'), ('MANAGER', 'Operations Manager')], max_length=50),
        ),
    ]
