# Generated by Django 3.2.6 on 2021-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('OFFICER', 'Distribution Officer'), ('SALESPERSON', 'Salesperson'), ('MANAGER', 'Operations Manager')], max_length=50),
        ),
    ]
