# Generated by Django 3.2.6 on 2021-09-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('SALESPERSON', 'Salesperson'), ('OFFICER', 'Distribution Officer'), ('MANAGER', 'Operations Manager')], max_length=50),
        ),
    ]
