# Generated by Django 3.2.6 on 2021-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('OFFICER', 'Distribution Officer'), ('MANAGER', 'Operations Manager'), ('SALESPERSON', 'Salesperson')], max_length=50),
        ),
    ]
