# Generated by Django 3.2.6 on 2021-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_staff_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('OFFICER', 'Distribution Officer'), ('SALESPERSON', 'Salesperson'), ('MANAGER', 'Operations Manager')], max_length=50),
        ),
    ]
