# Generated by Django 3.2.6 on 2021-09-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_staff_profile_picture'),
        ('users', '0024_alter_staff_user_role'),
    ]

    operations = [
    ]
