# Generated by Django 3.2.6 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210925_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.CharField(choices=[('OFFICER', 'Distribution Officer'), ('SALESPERSON', 'Salesperson'), ('MANAGER', 'Operations Manager')], max_length=50),
        ),
    ]
