# Generated by Django 3.2.6 on 2021-09-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('biscuit', 'Biscuit'), ('cake', 'Cake')], max_length=150),
        ),
    ]
