# Generated by Django 3.2.6 on 2021-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'Cake'), ('biscuit', 'Biscuit')], max_length=150),
        ),
    ]
