# Generated by Django 3.2.6 on 2021-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0010_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=80)),
                ('vehicle_type', models.CharField(choices=[('THREEWHEELER', 'threewheeler'), ('BIKE', 'bike'), ('VAN', 'Van'), ('LORRY', 'Lorry'), ('CAB', 'cab')], max_length=150)),
                ('vehicle_image', models.ImageField(max_length=255, upload_to='vehicle/')),
                ('vehicle_model', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'Cake'), ('biscuit', 'Biscuit')], max_length=150),
        ),
    ]
