# Generated by Django 3.2.6 on 2021-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0011_auto_20210922_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('biscuit', 'Biscuit'), ('cake', 'Cake')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('THREEWHEELER', 'threewheeler'), ('LORRY', 'Lorry'), ('VAN', 'Van'), ('BIKE', 'bike'), ('CAB', 'cab')], max_length=150),
        ),
    ]
