# Generated by Django 3.2.6 on 2021-09-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0013_auto_20210922_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('LORRY', 'Lorry'), ('THREEWHEELER', 'threewheeler'), ('CAB', 'cab'), ('VAN', 'Van'), ('BIKE', 'bike')], max_length=150),
        ),
        migrations.CreateModel(
            name='VehicleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_products', to='asset_api.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vehicle', to='asset_api.vehicle')),
            ],
            options={
                'ordering': ['vehicle'],
                'unique_together': {('vehicle', 'product')},
            },
        ),
    ]
