# Generated by Django 3.2.6 on 2021-09-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0014_auto_20210923_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'bike'), ('VAN', 'Van'), ('LORRY', 'Lorry'), ('CAB', 'cab'), ('THREEWHEELER', 'threewheeler')], max_length=150),
        ),
    ]
