# Generated by Django 3.2.6 on 2021-09-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_api', '0016_auto_20210924_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('biscuit', 'Biscuit'), ('cake', 'Cake')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'bike'), ('CAB', 'cab'), ('LORRY', 'Lorry'), ('THREEWHEELER', 'threewheeler'), ('VAN', 'Van')], max_length=150),
        ),
        migrations.CreateModel(
            name='VehicleSalesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_assigner', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_salesperson', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_api.vehicle')),
            ],
            options={
                'ordering': ['vehicle'],
                'unique_together': {('vehicle', 'salesperson')},
            },
        ),
    ]
