# Generated by Django 3.2.6 on 2021-09-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0018_auto_20210924_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('biscuit', 'Biscuit'), ('cake', 'Cake')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('THREEWHEELER', 'threewheeler'), ('CAB', 'cab'), ('BIKE', 'bike'), ('LORRY', 'Lorry'), ('VAN', 'Van')], max_length=150),
        ),
    ]
