# Generated by Django 3.2.6 on 2021-10-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0020_auto_20210927_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleproduct',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclesalesperson',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cookies', 'Cookies'), ('chips', 'Chips'), ('biscuit', 'Biscuit'), ('cheese', 'Cheese')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('VAN', 'Van'), ('LORRY', 'Lorry'), ('BIKE', 'Bike'), ('THREEWHEELER', 'Threewheeler'), ('BUS', 'Bus'), ('CAB', 'Cab')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehiclesalesperson',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_items', to='asset_api.vehicle'),
        ),
    ]
