# Generated by Django 3.2.6 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0021_auto_20211018_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cheese', 'Cheese'), ('chips', 'Chips'), ('cookies', 'Cookies'), ('biscuit', 'Biscuit')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('VAN', 'Van'), ('BUS', 'Bus'), ('BIKE', 'Bike'), ('THREEWHEELER', 'Threewheeler'), ('CAB', 'Cab'), ('LORRY', 'Lorry')], max_length=150),
        ),
    ]
