# Generated by Django 3.2.6 on 2021-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0022_auto_20211102_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('snacks', 'Snacks'), ('cookies', 'Cookies'), ('cheese', 'Cheese'), ('sauce', 'Sauce'), ('chips', 'Chips'), ('biscuit', 'Biscuit')], max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('THREEWHEELER', 'Threewheeler'), ('BIKE', 'Bike'), ('CAB', 'Cab'), ('LORRY', 'Lorry'), ('VAN', 'Van')], max_length=150),
        ),
    ]
