# Generated by Django 3.2.6 on 2021-09-17 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=225)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(max_length=255, upload_to='customer/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Badulla', 'Badulla'), ('Puttalam', 'Puttalam'), ('Jaffna', 'Jaffna'), ('Kalutara', 'Kalutara'), ('Anuradhapura', 'Anuradhapura'), ('Kandy', 'Kandy'), ('Ampara', 'Ampara'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Mullaitivu', 'Mullaitivu'), ('Monaragala', 'Monaragala'), ('Trincomalee', 'Trincomalee'), ('Matale', 'Matale'), ('Hambantota', 'Hambantota'), ('Polonnaruwa', 'Polonnaruwa'), ('Colombo', 'Colombo'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Matara', 'Matara'), ('Kegalle', 'Kegalle'), ('Kurunegala', 'Kurunegala'), ('Ratnapura', 'Ratnapura'), ('Vavuniya', 'Vavuniya'), ('Kilinochchi', 'Kilinochchi'), ('Batticaloa', 'Batticaloa'), ('Mannar', 'Mannar')], max_length=100)),
                ('loyalty_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
