# Generated by Django 3.2.6 on 2021-09-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0002_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Mannar', 'Mannar'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kalutara', 'Kalutara'), ('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Trincomalee', 'Trincomalee'), ('Anuradhapura', 'Anuradhapura'), ('Hambantota', 'Hambantota'), ('Vavuniya', 'Vavuniya'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Mullaitivu', 'Mullaitivu'), ('Polonnaruwa', 'Polonnaruwa'), ('Matale', 'Matale'), ('Kilinochchi', 'Kilinochchi'), ('Puttalam', 'Puttalam'), ('Matara', 'Matara'), ('Ampara', 'Ampara'), ('Gampaha', 'Gampaha'), ('Kurunegala', 'Kurunegala'), ('Monaragala', 'Monaragala'), ('Kegalle', 'Kegalle'), ('Kandy', 'Kandy'), ('Ratnapura', 'Ratnapura'), ('Badulla', 'Badulla')], max_length=100),
        ),
    ]
