# Generated by Django 3.2.6 on 2021-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0003_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kurunegala', 'Kurunegala'), ('Ampara', 'Ampara'), ('Vavuniya', 'Vavuniya'), ('Badulla', 'Badulla'), ('Hambantota', 'Hambantota'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Kilinochchi', 'Kilinochchi'), ('Monaragala', 'Monaragala'), ('Jaffna', 'Jaffna'), ('Kalutara', 'Kalutara'), ('Matara', 'Matara'), ('Polonnaruwa', 'Polonnaruwa'), ('Batticaloa', 'Batticaloa'), ('Gampaha', 'Gampaha'), ('Matale', 'Matale'), ('Mannar', 'Mannar'), ('Anuradhapura', 'Anuradhapura'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kegalle', 'Kegalle'), ('Puttalam', 'Puttalam'), ('Trincomalee', 'Trincomalee'), ('Kandy', 'Kandy'), ('Mullaitivu', 'Mullaitivu'), ('Ratnapura', 'Ratnapura')], max_length=100),
        ),
    ]
