# Generated by Django 3.2.6 on 2021-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0004_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Mannar', 'Mannar'), ('Ratnapura', 'Ratnapura'), ('Trincomalee', 'Trincomalee'), ('Anuradhapura', 'Anuradhapura'), ('Ampara', 'Ampara'), ('Vavuniya', 'Vavuniya'), ('Puttalam', 'Puttalam'), ('Polonnaruwa', 'Polonnaruwa'), ('Kegalle', 'Kegalle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Mullaitivu', 'Mullaitivu'), ('Jaffna', 'Jaffna'), ('Galle', 'Galle'), ('Batticaloa', 'Batticaloa'), ('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Kalutara', 'Kalutara'), ('Matara', 'Matara'), ('Matale', 'Matale'), ('Monaragala', 'Monaragala'), ('Kilinochchi', 'Kilinochchi'), ('Kurunegala', 'Kurunegala'), ('Badulla', 'Badulla'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota')], max_length=100),
        ),
    ]
