# Generated by Django 3.2.6 on 2021-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0005_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Badulla', 'Badulla'), ('Ampara', 'Ampara'), ('Gampaha', 'Gampaha'), ('Kegalle', 'Kegalle'), ('Polonnaruwa', 'Polonnaruwa'), ('Kalutara', 'Kalutara'), ('Anuradhapura', 'Anuradhapura'), ('Hambantota', 'Hambantota'), ('Puttalam', 'Puttalam'), ('Mannar', 'Mannar'), ('Matale', 'Matale'), ('Kurunegala', 'Kurunegala'), ('Kandy', 'Kandy'), ('Kilinochchi', 'Kilinochchi'), ('Colombo', 'Colombo'), ('Matara', 'Matara'), ('Mullaitivu', 'Mullaitivu'), ('Trincomalee', 'Trincomalee'), ('Monaragala', 'Monaragala'), ('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Vavuniya', 'Vavuniya'), ('Ratnapura', 'Ratnapura')], max_length=100),
        ),
    ]
