# Generated by Django 3.2.6 on 2021-09-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_api', '0006_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Puttalam', 'Puttalam'), ('Galle', 'Galle'), ('Jaffna', 'Jaffna'), ('Colombo', 'Colombo'), ('Hambantota', 'Hambantota'), ('Gampaha', 'Gampaha'), ('Matara', 'Matara'), ('Mannar', 'Mannar'), ('Badulla', 'Badulla'), ('Kegalle', 'Kegalle'), ('Kandy', 'Kandy'), ('Trincomalee', 'Trincomalee'), ('Ampara', 'Ampara'), ('Polonnaruwa', 'Polonnaruwa'), ('Vavuniya', 'Vavuniya'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ratnapura', 'Ratnapura'), ('Mullaitivu', 'Mullaitivu'), ('Anuradhapura', 'Anuradhapura'), ('Monaragala', 'Monaragala'), ('Matale', 'Matale'), ('Batticaloa', 'Batticaloa'), ('Kurunegala', 'Kurunegala'), ('Kalutara', 'Kalutara'), ('Kilinochchi', 'Kilinochchi')], max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_api.customer')),
                ('salesperson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
