# Generated by Django 3.2.6 on 2021-09-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0008_auto_20210918_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kegalle', 'Kegalle'), ('Mannar', 'Mannar'), ('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Kilinochchi', 'Kilinochchi'), ('Mullaitivu', 'Mullaitivu'), ('Galle', 'Galle'), ('Monaragala', 'Monaragala'), ('Gampaha', 'Gampaha'), ('Hambantota', 'Hambantota'), ('Vavuniya', 'Vavuniya'), ('Ratnapura', 'Ratnapura'), ('Puttalam', 'Puttalam'), ('Badulla', 'Badulla'), ('Trincomalee', 'Trincomalee'), ('Polonnaruwa', 'Polonnaruwa'), ('Kalutara', 'Kalutara'), ('Anuradhapura', 'Anuradhapura'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Ampara', 'Ampara'), ('Matara', 'Matara'), ('Matale', 'Matale'), ('Kurunegala', 'Kurunegala')], max_length=100),
        ),
    ]
