# Generated by Django 3.2.6 on 2021-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0009_alter_customer_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='salesperson_id',
            new_name='salesperson',
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Puttalam', 'Puttalam'), ('Kegalle', 'Kegalle'), ('Trincomalee', 'Trincomalee'), ('Kalutara', 'Kalutara'), ('Batticaloa', 'Batticaloa'), ('Galle', 'Galle'), ('Badulla', 'Badulla'), ('Vavuniya', 'Vavuniya'), ('Mullaitivu', 'Mullaitivu'), ('Ampara', 'Ampara'), ('Jaffna', 'Jaffna'), ('Matara', 'Matara'), ('Polonnaruwa', 'Polonnaruwa'), ('Kilinochchi', 'Kilinochchi'), ('Hambantota', 'Hambantota'), ('Kandy', 'Kandy'), ('Anuradhapura', 'Anuradhapura'), ('Matale', 'Matale'), ('Ratnapura', 'Ratnapura'), ('Mannar', 'Mannar'), ('Monaragala', 'Monaragala'), ('Kurunegala', 'Kurunegala'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Colombo', 'Colombo'), ('Gampaha', 'Gampaha')], max_length=100),
        ),
    ]
