# Generated by Django 3.2.6 on 2021-09-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0006_alter_product_category'),
        ('customer_api', '0010_auto_20210918_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Polonnaruwa', 'Polonnaruwa'), ('Mannar', 'Mannar'), ('Batticaloa', 'Batticaloa'), ('Kandy', 'Kandy'), ('Colombo', 'Colombo'), ('Mullaitivu', 'Mullaitivu'), ('Jaffna', 'Jaffna'), ('Monaragala', 'Monaragala'), ('Ratnapura', 'Ratnapura'), ('Hambantota', 'Hambantota'), ('Anuradhapura', 'Anuradhapura'), ('Kalutara', 'Kalutara'), ('Kilinochchi', 'Kilinochchi'), ('Trincomalee', 'Trincomalee'), ('Matara', 'Matara'), ('Ampara', 'Ampara'), ('Puttalam', 'Puttalam'), ('Badulla', 'Badulla'), ('Kurunegala', 'Kurunegala'), ('Kegalle', 'Kegalle'), ('Vavuniya', 'Vavuniya'), ('Matale', 'Matale'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Gampaha', 'Gampaha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='customer_api.serviceorder'),
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product')},
        ),
    ]
