# Generated by Django 3.2.6 on 2021-09-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0012_auto_20210919_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Batticaloa', 'Batticaloa'), ('Puttalam', 'Puttalam'), ('Gampaha', 'Gampaha'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Matale', 'Matale'), ('Trincomalee', 'Trincomalee'), ('Galle', 'Galle'), ('Mannar', 'Mannar'), ('Vavuniya', 'Vavuniya'), ('Anuradhapura', 'Anuradhapura'), ('Polonnaruwa', 'Polonnaruwa'), ('Kilinochchi', 'Kilinochchi'), ('Badulla', 'Badulla'), ('Matara', 'Matara'), ('Mullaitivu', 'Mullaitivu'), ('Jaffna', 'Jaffna'), ('Monaragala', 'Monaragala'), ('Kandy', 'Kandy'), ('Ampara', 'Ampara'), ('Kegalle', 'Kegalle'), ('Colombo', 'Colombo'), ('Kurunegala', 'Kurunegala'), ('Kalutara', 'Kalutara'), ('Ratnapura', 'Ratnapura'), ('Hambantota', 'Hambantota')], max_length=100),
        ),
    ]
