# Generated by Django 3.2.6 on 2021-09-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0013_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kilinochchi', 'Kilinochchi'), ('Mullaitivu', 'Mullaitivu'), ('Polonnaruwa', 'Polonnaruwa'), ('Matale', 'Matale'), ('Monaragala', 'Monaragala'), ('Hambantota', 'Hambantota'), ('Badulla', 'Badulla'), ('Puttalam', 'Puttalam'), ('Jaffna', 'Jaffna'), ('Colombo', 'Colombo'), ('Batticaloa', 'Batticaloa'), ('Kandy', 'Kandy'), ('Ampara', 'Ampara'), ('Mannar', 'Mannar'), ('Ratnapura', 'Ratnapura'), ('Vavuniya', 'Vavuniya'), ('Anuradhapura', 'Anuradhapura'), ('Kurunegala', 'Kurunegala'), ('Galle', 'Galle'), ('Kegalle', 'Kegalle'), ('Kalutara', 'Kalutara'), ('Matara', 'Matara'), ('Trincomalee', 'Trincomalee'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Gampaha', 'Gampaha')], max_length=100),
        ),
    ]
