# Generated by Django 3.2.6 on 2021-09-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0014_alter_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price_at_the_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Ratnapura', 'Ratnapura'), ('Matale', 'Matale'), ('Anuradhapura', 'Anuradhapura'), ('Mullaitivu', 'Mullaitivu'), ('Mannar', 'Mannar'), ('Badulla', 'Badulla'), ('Monaragala', 'Monaragala'), ('Kalutara', 'Kalutara'), ('Kilinochchi', 'Kilinochchi'), ('Kegalle', 'Kegalle'), ('Ampara', 'Ampara'), ('Jaffna', 'Jaffna'), ('Kurunegala', 'Kurunegala'), ('Trincomalee', 'Trincomalee'), ('Polonnaruwa', 'Polonnaruwa'), ('Vavuniya', 'Vavuniya'), ('Galle', 'Galle'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Puttalam', 'Puttalam'), ('Batticaloa', 'Batticaloa'), ('Gampaha', 'Gampaha'), ('Matara', 'Matara'), ('Colombo', 'Colombo'), ('Hambantota', 'Hambantota'), ('Kandy', 'Kandy')], max_length=100),
        ),
    ]
