# Generated by Django 3.2.6 on 2021-09-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0007_alter_product_category'),
        ('customer_api', '0015_auto_20210919_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kurunegala', 'Kurunegala'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Badulla', 'Badulla'), ('Mullaitivu', 'Mullaitivu'), ('Vavuniya', 'Vavuniya'), ('Kandy', 'Kandy'), ('Kilinochchi', 'Kilinochchi'), ('Matale', 'Matale'), ('Ratnapura', 'Ratnapura'), ('Hambantota', 'Hambantota'), ('Mannar', 'Mannar'), ('Monaragala', 'Monaragala'), ('Trincomalee', 'Trincomalee'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Kegalle', 'Kegalle'), ('Polonnaruwa', 'Polonnaruwa'), ('Kalutara', 'Kalutara'), ('Puttalam', 'Puttalam'), ('Colombo', 'Colombo'), ('Batticaloa', 'Batticaloa'), ('Ampara', 'Ampara'), ('Jaffna', 'Jaffna'), ('Anuradhapura', 'Anuradhapura'), ('Matara', 'Matara')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='asset_api.product'),
        ),
    ]
