# Generated by Django 3.2.6 on 2021-09-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_api', '0007_alter_product_category'),
        ('customer_api', '0015_auto_20210919_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyaltyPointScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('point_percentage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Ampara', 'Ampara'), ('Gampaha', 'Gampaha'), ('Mannar', 'Mannar'), ('Matale', 'Matale'), ('Kandy', 'Kandy'), ('Anuradhapura', 'Anuradhapura'), ('Jaffna', 'Jaffna'), ('Puttalam', 'Puttalam'), ('Colombo', 'Colombo'), ('Hambantota', 'Hambantota'), ('Galle', 'Galle'), ('Kalutara', 'Kalutara'), ('Trincomalee', 'Trincomalee'), ('Kurunegala', 'Kurunegala'), ('Ratnapura', 'Ratnapura'), ('Matara', 'Matara'), ('Mullaitivu', 'Mullaitivu'), ('Polonnaruwa', 'Polonnaruwa'), ('Kilinochchi', 'Kilinochchi'), ('Batticaloa', 'Batticaloa'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Vavuniya', 'Vavuniya'), ('Monaragala', 'Monaragala'), ('Badulla', 'Badulla'), ('Kegalle', 'Kegalle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='asset_api.product'),
        ),
    ]
