# Generated by Django 3.2.6 on 2021-09-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0017_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Hambantota', 'Hambantota'), ('Kegalle', 'Kegalle'), ('Galle', 'Galle'), ('Gampaha', 'Gampaha'), ('Monaragala', 'Monaragala'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Trincomalee', 'Trincomalee'), ('Vavuniya', 'Vavuniya'), ('Kandy', 'Kandy'), ('Polonnaruwa', 'Polonnaruwa'), ('Kurunegala', 'Kurunegala'), ('Ampara', 'Ampara'), ('Matara', 'Matara'), ('Colombo', 'Colombo'), ('Matale', 'Matale'), ('Jaffna', 'Jaffna'), ('Anuradhapura', 'Anuradhapura'), ('Puttalam', 'Puttalam'), ('Kalutara', 'Kalutara'), ('Mannar', 'Mannar'), ('Batticaloa', 'Batticaloa'), ('Mullaitivu', 'Mullaitivu'), ('Badulla', 'Badulla'), ('Ratnapura', 'Ratnapura'), ('Kilinochchi', 'Kilinochchi')], max_length=100),
        ),
    ]
