# Generated by Django 3.2.6 on 2021-09-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0016_auto_20210919_1748'),
        ('customer_api', '0018_alter_customer_district'),
    ]

    operations = [
    ]
