# Generated by Django 3.2.6 on 2021-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0019_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Batticaloa', 'Batticaloa'), ('Jaffna', 'Jaffna'), ('Puttalam', 'Puttalam'), ('Kandy', 'Kandy'), ('Kurunegala', 'Kurunegala'), ('Ratnapura', 'Ratnapura'), ('Colombo', 'Colombo'), ('Galle', 'Galle'), ('Mullaitivu', 'Mullaitivu'), ('Kegalle', 'Kegalle'), ('Anuradhapura', 'Anuradhapura'), ('Kalutara', 'Kalutara'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Kilinochchi', 'Kilinochchi'), ('Mannar', 'Mannar'), ('Gampaha', 'Gampaha'), ('Ampara', 'Ampara'), ('Hambantota', 'Hambantota'), ('Polonnaruwa', 'Polonnaruwa'), ('Matale', 'Matale'), ('Matara', 'Matara'), ('Monaragala', 'Monaragala'), ('Vavuniya', 'Vavuniya'), ('Trincomalee', 'Trincomalee'), ('Badulla', 'Badulla')], max_length=100),
        ),
    ]
