# Generated by Django 3.2.6 on 2021-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0020_auto_20210920_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Trincomalee', 'Trincomalee'), ('Kalutara', 'Kalutara'), ('Puttalam', 'Puttalam'), ('Badulla', 'Badulla'), ('Kilinochchi', 'Kilinochchi'), ('Mullaitivu', 'Mullaitivu'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Vavuniya', 'Vavuniya'), ('Ampara', 'Ampara'), ('Anuradhapura', 'Anuradhapura'), ('Kandy', 'Kandy'), ('Colombo', 'Colombo'), ('Kegalle', 'Kegalle'), ('Polonnaruwa', 'Polonnaruwa'), ('Ratnapura', 'Ratnapura'), ('Hambantota', 'Hambantota'), ('Mannar', 'Mannar'), ('Galle', 'Galle'), ('Kurunegala', 'Kurunegala'), ('Matara', 'Matara'), ('Monaragala', 'Monaragala'), ('Jaffna', 'Jaffna'), ('Matale', 'Matale'), ('Batticaloa', 'Batticaloa'), ('Gampaha', 'Gampaha')], max_length=100),
        ),
    ]
