# Generated by Django 3.2.6 on 2021-09-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0021_auto_20210923_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Badulla', 'Badulla'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Colombo', 'Colombo'), ('Ratnapura', 'Ratnapura'), ('Puttalam', 'Puttalam'), ('Mullaitivu', 'Mullaitivu'), ('Kegalle', 'Kegalle'), ('Kalutara', 'Kalutara'), ('Trincomalee', 'Trincomalee'), ('Anuradhapura', 'Anuradhapura'), ('Mannar', 'Mannar'), ('Kurunegala', 'Kurunegala'), ('Monaragala', 'Monaragala'), ('Kilinochchi', 'Kilinochchi'), ('Matale', 'Matale'), ('Kandy', 'Kandy'), ('Hambantota', 'Hambantota'), ('Ampara', 'Ampara'), ('Vavuniya', 'Vavuniya'), ('Gampaha', 'Gampaha'), ('Jaffna', 'Jaffna'), ('Matara', 'Matara'), ('Polonnaruwa', 'Polonnaruwa'), ('Galle', 'Galle'), ('Batticaloa', 'Batticaloa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
