# Generated by Django 3.2.6 on 2021-09-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0021_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Batticaloa', 'Batticaloa'), ('Kegalle', 'Kegalle'), ('Puttalam', 'Puttalam'), ('Kilinochchi', 'Kilinochchi'), ('Gampaha', 'Gampaha'), ('Polonnaruwa', 'Polonnaruwa'), ('Trincomalee', 'Trincomalee'), ('Kalutara', 'Kalutara'), ('Matale', 'Matale'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Matara', 'Matara'), ('Jaffna', 'Jaffna'), ('Galle', 'Galle'), ('Anuradhapura', 'Anuradhapura'), ('Badulla', 'Badulla'), ('Monaragala', 'Monaragala'), ('Kandy', 'Kandy'), ('Colombo', 'Colombo'), ('Vavuniya', 'Vavuniya'), ('Ratnapura', 'Ratnapura'), ('Mullaitivu', 'Mullaitivu'), ('Ampara', 'Ampara'), ('Mannar', 'Mannar'), ('Hambantota', 'Hambantota'), ('Kurunegala', 'Kurunegala')], max_length=100),
        ),
    ]
