# Generated by Django 3.2.6 on 2021-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0022_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Mannar', 'Mannar'), ('Matara', 'Matara'), ('Gampaha', 'Gampaha'), ('Badulla', 'Badulla'), ('Kegalle', 'Kegalle'), ('Colombo', 'Colombo'), ('Matale', 'Matale'), ('Mullaitivu', 'Mullaitivu'), ('Ampara', 'Ampara'), ('Jaffna', 'Jaffna'), ('Anuradhapura', 'Anuradhapura'), ('Ratnapura', 'Ratnapura'), ('Kurunegala', 'Kurunegala'), ('Kalutara', 'Kalutara'), ('Puttalam', 'Puttalam'), ('Galle', 'Galle'), ('Kilinochchi', 'Kilinochchi'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Monaragala', 'Monaragala'), ('Vavuniya', 'Vavuniya'), ('Hambantota', 'Hambantota'), ('Polonnaruwa', 'Polonnaruwa'), ('Kandy', 'Kandy'), ('Trincomalee', 'Trincomalee'), ('Batticaloa', 'Batticaloa')], max_length=100),
        ),
    ]
