# Generated by Django 3.2.6 on 2021-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0024_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Mullaitivu', 'Mullaitivu'), ('Kurunegala', 'Kurunegala'), ('Batticaloa', 'Batticaloa'), ('Hambantota', 'Hambantota'), ('Trincomalee', 'Trincomalee'), ('Vavuniya', 'Vavuniya'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Polonnaruwa', 'Polonnaruwa'), ('Kilinochchi', 'Kilinochchi'), ('Badulla', 'Badulla'), ('Anuradhapura', 'Anuradhapura'), ('Gampaha', 'Gampaha'), ('Monaragala', 'Monaragala'), ('Kegalle', 'Kegalle'), ('Kandy', 'Kandy'), ('Matale', 'Matale'), ('Jaffna', 'Jaffna'), ('Ampara', 'Ampara'), ('Galle', 'Galle'), ('Matara', 'Matara'), ('Kalutara', 'Kalutara'), ('Ratnapura', 'Ratnapura'), ('Mannar', 'Mannar'), ('Colombo', 'Colombo'), ('Puttalam', 'Puttalam')], max_length=100),
        ),
    ]
