# Generated by Django 3.2.6 on 2021-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0025_alter_customer_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Nuwara Eliya', 'Nuwara Eliya'), ('Badulla', 'Badulla'), ('Vavuniya', 'Vavuniya'), ('Matara', 'Matara'), ('Kurunegala', 'Kurunegala'), ('Polonnaruwa', 'Polonnaruwa'), ('Matale', 'Matale'), ('Batticaloa', 'Batticaloa'), ('Mullaitivu', 'Mullaitivu'), ('Hambantota', 'Hambantota'), ('Jaffna', 'Jaffna'), ('Kalutara', 'Kalutara'), ('Ampara', 'Ampara'), ('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Trincomalee', 'Trincomalee'), ('Anuradhapura', 'Anuradhapura'), ('Kilinochchi', 'Kilinochchi'), ('Puttalam', 'Puttalam'), ('Ratnapura', 'Ratnapura'), ('Monaragala', 'Monaragala'), ('Kegalle', 'Kegalle'), ('Mannar', 'Mannar'), ('Gampaha', 'Gampaha'), ('Galle', 'Galle')], max_length=100),
        ),
    ]
