# Generated by Django 3.2.6 on 2021-09-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0022_auto_20210923_0907'),
        ('customer_api', '0026_alter_customer_district'),
    ]

    operations = [
    ]
