# Generated by Django 3.2.6 on 2021-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0029_auto_20210926_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Anuradhapura', 'Anuradhapura'), ('Ampara', 'Ampara'), ('Kandy', 'Kandy'), ('Mullaitivu', 'Mullaitivu'), ('Kilinochchi', 'Kilinochchi'), ('Kalutara', 'Kalutara'), ('Puttalam', 'Puttalam'), ('Colombo', 'Colombo'), ('Trincomalee', 'Trincomalee'), ('Hambantota', 'Hambantota'), ('Mannar', 'Mannar'), ('Jaffna', 'Jaffna'), ('Matale', 'Matale'), ('Galle', 'Galle'), ('Vavuniya', 'Vavuniya'), ('Monaragala', 'Monaragala'), ('Gampaha', 'Gampaha'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ratnapura', 'Ratnapura'), ('Kegalle', 'Kegalle'), ('Matara', 'Matara'), ('Batticaloa', 'Batticaloa'), ('Polonnaruwa', 'Polonnaruwa'), ('Kurunegala', 'Kurunegala'), ('Badulla', 'Badulla')], max_length=100),
        ),
    ]
