# Generated by Django 3.2.6 on 2021-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0030_auto_20210930_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerloyaltypointscheme',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='customerloyaltypointscheme',
            name='minimum_amount',
        ),
        migrations.RemoveField(
            model_name='customerloyaltypointscheme',
            name='point_percentage',
        ),
        migrations.AddField(
            model_name='customerloyaltypointscheme',
            name='bonus_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='customerloyaltypointscheme',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='customerloyaltypointscheme',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('SO_PAY_LATER', 'SO pay later'), ('LATE_PAYMENTS', 'Late Payments')], default='LATE_PAYMENTS', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kegalle', 'Kegalle'), ('Colombo', 'Colombo'), ('Kalutara', 'Kalutara'), ('Ratnapura', 'Ratnapura'), ('Mullaitivu', 'Mullaitivu'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Ampara', 'Ampara'), ('Hambantota', 'Hambantota'), ('Batticaloa', 'Batticaloa'), ('Kurunegala', 'Kurunegala'), ('Badulla', 'Badulla'), ('Trincomalee', 'Trincomalee'), ('Monaragala', 'Monaragala'), ('Kilinochchi', 'Kilinochchi'), ('Jaffna', 'Jaffna'), ('Puttalam', 'Puttalam'), ('Matale', 'Matale'), ('Vavuniya', 'Vavuniya'), ('Gampaha', 'Gampaha'), ('Galle', 'Galle'), ('Matara', 'Matara'), ('Kandy', 'Kandy'), ('Anuradhapura', 'Anuradhapura'), ('Polonnaruwa', 'Polonnaruwa'), ('Mannar', 'Mannar')], max_length=100),
        ),
    ]
