# Generated by Django 3.2.6 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0031_auto_20211030_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Galle', 'Galle'), ('Polonnaruwa', 'Polonnaruwa'), ('Kandy', 'Kandy'), ('Kurunegala', 'Kurunegala'), ('Mullaitivu', 'Mullaitivu'), ('Trincomalee', 'Trincomalee'), ('Hambantota', 'Hambantota'), ('Kalutara', 'Kalutara'), ('Kilinochchi', 'Kilinochchi'), ('Puttalam', 'Puttalam'), ('Mannar', 'Mannar'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Colombo', 'Colombo'), ('Ratnapura', 'Ratnapura'), ('Monaragala', 'Monaragala'), ('Batticaloa', 'Batticaloa'), ('Kegalle', 'Kegalle'), ('Badulla', 'Badulla'), ('Matara', 'Matara'), ('Anuradhapura', 'Anuradhapura'), ('Ampara', 'Ampara'), ('Vavuniya', 'Vavuniya'), ('Matale', 'Matale'), ('Jaffna', 'Jaffna'), ('Gampaha', 'Gampaha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerloyaltypointscheme',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('LATE_PAYMENTS', 'Late Payments'), ('SO_PAY_LATER', 'SO pay later')], default='LATE_PAYMENTS', max_length=100),
        ),
    ]
