# Generated by Django 3.2.6 on 2021-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0032_auto_20211102_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Jaffna', 'Jaffna'), ('Monaragala', 'Monaragala'), ('Hambantota', 'Hambantota'), ('Ampara', 'Ampara'), ('Matale', 'Matale'), ('Galle', 'Galle'), ('Batticaloa', 'Batticaloa'), ('Gampaha', 'Gampaha'), ('Ratnapura', 'Ratnapura'), ('Kalutara', 'Kalutara'), ('Nuwara Eliya', 'Nuwara Eliya'), ('Puttalam', 'Puttalam'), ('Kilinochchi', 'Kilinochchi'), ('Kurunegala', 'Kurunegala'), ('Mannar', 'Mannar'), ('Trincomalee', 'Trincomalee'), ('Badulla', 'Badulla'), ('Matara', 'Matara'), ('Colombo', 'Colombo'), ('Anuradhapura', 'Anuradhapura'), ('Kegalle', 'Kegalle'), ('Polonnaruwa', 'Polonnaruwa'), ('Kandy', 'Kandy'), ('Vavuniya', 'Vavuniya'), ('Mullaitivu', 'Mullaitivu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerloyaltypointscheme',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('SO_PAY_LATER', 'SO pay later'), ('LATE_PAYMENTS', 'Late Payments')], default='LATE_PAYMENTS', max_length=100),
        ),
    ]
