# Generated by Django 3.2.6 on 2021-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0003_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardPointSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_type', models.CharField(choices=[('LATE_PAYMENTS', 'Late Payments'), ('SO', 'Service Orders'), ('ITEM_COUNT', 'Item Count')], max_length=100)),
                ('price_lowerbound', models.DecimalField(decimal_places=2, max_digits=11)),
                ('price_upperbound', models.DecimalField(decimal_places=2, max_digits=11)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bonus_points', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
