# Generated by Django 3.2.6 on 2021-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0008_alter_leaderboardpointschema_points_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('ITEM_COUNT', 'Item Count'), ('SO', 'Service Orders'), ('LATE_PAYMENTS', 'Late Payments')], max_length=100),
        ),
    ]
