# Generated by Django 3.2.6 on 2021-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0010_alter_leaderboardpointschema_points_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('SO', 'Service Orders'), ('LATE_PAYMENTS', 'Late Payments'), ('ITEM_COUNT', 'Item Count')], max_length=100),
        ),
    ]
