# Generated by Django 3.2.6 on 2021-09-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0011_alter_leaderboardpointschema_points_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardpointschema',
            name='price_lowerbound',
        ),
        migrations.RemoveField(
            model_name='leaderboardpointschema',
            name='price_upperbound',
        ),
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('SO', 'Service Orders'), ('ITEM_COUNT', 'Item Count'), ('LATE_PAYMENTS', 'Late Payments')], max_length=100),
        ),
    ]
