# Generated by Django 3.2.6 on 2021-09-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0012_auto_20210925_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('CUSTOMER_CREATION', 'customer creation'), ('SO_PAY_LATEr', 'SO pay later'), ('LATE_PAYMENTS', 'Late Payments')], max_length=100),
        ),
    ]
