# Generated by Django 3.2.6 on 2021-11-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0014_alter_leaderboardpointschema_points_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('LATE_PAYMENTS', 'Late Payments'), ('CUSTOMER_CREATION', 'customer creation'), ('SO_PAY_LATER', 'SO pay later')], max_length=100),
        ),
    ]
