# Generated by Django 3.2.6 on 2021-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson_api', '0015_alter_leaderboardpointschema_points_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardpointschema',
            name='points_type',
            field=models.CharField(choices=[('SO_PAY', 'SO payed'), ('SO_PAY_LATER', 'SO pay later'), ('LATE_PAYMENTS', 'Late Payments'), ('CUSTOMER_CREATION', 'customer creation')], max_length=100),
        ),
    ]
